; use with llama.cpp: llama-server.exe --models-preset llama-config.ini --models-max 1 --port 11434
; for model args: https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md
; for server args: https://github.com/ggml-org/llama.cpp/blob/master/docs/preset.md

[*]
no-ui = true

n-gpu-layers = all
fit-target = 128
flash-attn = on
cache-type-k = q8_0
cache-type-v = q8_0

no-mmap = true
cache-ram = 0
no-cache-prompt = true
no-cache-idle-slots = true
batch-size = 8192
ubatch-size = 2048

[default]
load-on-startup = true
alias = gemma4
;; src: hf://mradermacher/gemma-4-E4B-it-qat-q4_0-unquantized-heretic-i1-GGUF
model = gemma-4-E4B-it-qat-q4_0-unquantized-heretic.i1-Q4_K_M.gguf
;; src: hf://mradermacher/gemma-4-E4B-it-qat-q4_0-unquantized-GGUF
; mmproj = gemma-4-E4B-it-qat-q4_0-unquantized.mmproj-Q8_0.gguf

;; context size per slot = total ÷ number of slots (unless set kv-unified but maybe out-of-memory)
parallel = 2
; split-mode = tensor
;; context: 2¹³ = 8192 / 16384 / 32768 / 65536 / 131072 / 262144 / 524288 / 1048576 = 2²⁰
; ctx-size = 32768
;; processing speed for very long prompt become decrease over time
swa-full = true
swa-checkpoints = 0

reasoning = off
temperature = 0.3
top-p = 0.95
top-k = 64
min-p = 0.0
repeat-penalty = 1.05
; jinja = true
; tools = all

;; ATTENTION: multi-token prediction may be fast with agents, but slower for accuracy-critical tasks
;; hf://unsloth/gemma-4-E4B-it-qat-GGUF
; spec-model-draft = gemma-4-E4B-it-Q8_0-MTP.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 2
; spec-draft-ngl = all
; spec-draft-type-k = q8_0
; spec-draft-type-v = q8_0
