; use with llama.cpp: llama-server.exe --models-preset llama-config.ini

; port = 11434 ; default = 8080
no-ui = true

alias = gemma4
model = gemma-4-12B-it-qat-q4_0-unquantized-uncensored-heretic.i1-Q4_K_M.gguf ; hf://mradermacher/gemma-4-E4B-it-qat-q4_0-unquantized-heretic-i1-GGUF
; mmproj = gemma-4-E4B-it-qat-q4_0-unquantized.mmproj-Q8_0.gguf ; hf://mradermacher/gemma-4-E4B-it-qat-q4_0-unquantized-GGUF
; spec-model-draft = gemma-4-E4B-it-Q8_0-MTP.gguf ; hf://unsloth/gemma-4-E4B-it-qat-GGUF
; spec-type = draft-mtp
; spec-draft-n-max = 2

; cpu-moe = true
; spec-draft-cpu-moe = true
n-gpu-layers = all
; n-gpu-layers-draft = all
; split-mode = tensor
fit-target = 128
; ctx-size = 32768 ; 8192/16384/32768/65536/131072/262144/524288/1048576

no-mmap = true
cache-ram = 0
no-cache-prompt = true
no-cache-idle-slots = true
batch-size = 1024
ubatch-size = 256
parallel = 1

swa-full = true
swa-checkpoints = 0
flash-attn = on
cache-type-k = q8_0
cache-type-v = q8_0
; spec-draft-type-k = q8_0
; spec-draft-type-v = q8_0

reasoning = off
temperature = 0.3
top-p = 0.95
top-k = 64
min-p = 0.0
repeat-penalty = 1.05
; jinja = true
; tools = all
