# contents go to <mpv install dir>/portable_config/mpv.conf
# remember to change profile + resolution + codec accordingly to gpu
# need to download quickjs for yt-dlp: https://github.com/yt-dlp/yt-dlp/wiki/EJS

profile = fast
# profile = high-quality
# deband = yes
# deband-iterations = 4
# deband-threshold = 48
# deband-range = 24
# deband-grain = 16
# dither-depth = auto
# dither = error-diffusion
# error-diffusion = sierra-lite

vo = gpu-next
hwdec = auto
hwdec-codecs = all
hwdec-threads = 0
vd-lavc-dr = yes
icc-profile-auto

cursor-autohide = no
keep-open = yes
volume = 100
volume-max = 100
window-maximized = yes
auto-window-resize = no
keepaspect-window = no
autofit-larger = 100%x100%
osd-bar = no
osd-scale-by-window = no
script-opts = 'timetotal=yes,remaining_playtime=no'

ytdl-format = (bestvideo+bestaudio/best)[height<=?2160][vcodec!*=av01]
target-colorspace-hint = auto
video-sync = display-resample
interpolation = yes
tscale = mitchell
scale-param1 = 0.5
scale-param2 = 0.5
tscale-clamp = 0.2
tscale-antiring = 0.2
tscale-blur = 0.7
tscale-window = sphinx

sub-border-style = opaque-box
sub-font-size = 18
sub-auto = fuzzy
slang = en,fr,vi
ytdl-raw-options = 'sub-langs="en.*,fr.*,vi.*",write-subs=,write-auto-subs='
ytdl-raw-options-append = 'cookies-from-browser=firefox'
ytdl-raw-options-append = 'js-runtimes=quickjs:qjs-windows-x86_64.exe'
# ytdl-raw-options-append = 'sponsorblock-remove="sponsor,selfpromo,filler,interaction"'

[audio-only]
profile-cond = not vid and not vo_configured
script-opts-append = 'osc-visibility=always' # press Del
window-maximized = no
autofit-larger = 50%x50%
ytdl-format = bestaudio*
sub-visibility = no
input-commands = 'script-message display-stats-toggle' # press Shift+i
