REM must run as admin

POWERCFG /SETACTIVE SCHEME_MIN

POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMIN 0
POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMAX 100

POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMIN 0
POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMAX 90

POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_DISK DISKIDLE 0
POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_SLEEP STANDBYIDLE 0
POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_VIDEO VIDEOIDLE 0

POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_DISK DISKIDLE 600
POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_SLEEP STANDBYIDLE 600
POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_VIDEO VIDEOIDLE 600

POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_BUTTONS PBUTTONACTION 0
POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_BUTTONS LIDACTION 0

POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_BUTTONS PBUTTONACTION 0
POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_BUTTONS LIDACTION 1

POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATFLAGSCRIT 1
POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATFLAGSLOW 1
POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATACTIONCRIT 0
POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATACTIONLOW 0
POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATLEVELCRIT 5
POWERCFG /SETACVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATLEVELLOW 20

POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATFLAGSCRIT 1
POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATFLAGSLOW 1
POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATACTIONCRIT 0
POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATACTIONLOW 0
POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATLEVELCRIT 5
POWERCFG /SETDCVALUEINDEX SCHEME_CURRENT SUB_BATTERY BATLEVELLOW 20
