REM edit path before run

SETX XDG_CACHE_HOME ███:\cache
SETX HF_HOME ███:\cache
SETX PIP_CACHE_DIR ███:\cache
SETX UV_CACHE_DIR ███:\cache

SETX SIGIL_ALLOW_CODEVIEW_DROP 1
SETX SIGIL_DISABLE_VERSION_META 1
SETX SIGIL_PREVIEW_TIMEOUT 10000

SETX POWERSHELL_CLI_TELEMETRY_OPTOUT 1
SETX POWERSHELL_TELEMETRY_OPTOUT 1
SETX POWERSHELL_UPDATECHECK 0
SETX POWERSHELL_UPDATECHECK_OPTOUT 1
SETX DOTNET_CLI_TELEMETRY_OPTOUT 1
SETX DOTNET_TELEMETRY_OPTOUT 1
SETX COMPlus_EnableDiagnostics 0
